### ISSUE TITLE
creating files, Milestones

### ISSUE THREAD

**Issue by flomaurer** [Phillip-W/entwurf_vhdl_prozessor#1]
wir müssen es noch schaffen, dass auch wir (nicht "Projektlieuter") Datein erstellen können - ich fang jetzt mal mit der Entity vom Prozessor an und lad die dann hoch, sobald dies möglich ist.
Außerdem wär es cool, wenn jeder Meilensteine erstellen könnte - ist mir bisher noch nicht möglich

**Comment by Phillip-W** [comment]
Versuchs jetzt mal hab dich und patrick grad als collaborators hinzugefügt müsste also jetzt gehen.

**Comment by flomaurer** [comment]
funktioniert. - bis auf Milestones
Perfekt.
