### ISSUE TITLE
Range vom Integer

### ISSUE THREAD

**Issue by Sabbuth** [Phillip-W/entwurf_vhdl_prozessor#16]
Hallo Leute ich werde diesen Subtypen zum offiziellen subtypen für Berechnungen machen...

subtype IntegerForCalculation is integer range -2048 to 2047;

Also ich setze bei den Zahlen es einfach in Abhangigkeit von der Data_width dann ein

**Comment by Sabbuth** [comment]
Es wäre dan folgendes:

subtype IntegerForCalculation is integer range -2**(data_width-1) to 2**(data_width-1)-1;

**Comment by flomaurer** [comment]
OK.
Im Moment sehe ich zwar noch nicht, dass wir den brauchen.
Aber wir müssen alles nochmals überdenken - wir waren viel zu nah am RTL-Modell.
Meld dich mal bei mir.
