### ISSUE TITLE
bit or integer?

### ISSUE THREAD

**Issue by flomaurer** [Phillip-W/entwurf_vhdl_prozessor#2]
Hi Leute,
schreiben wir ein Bit- oder ein Integermodel.
Mir persönlich hat Integer mehr zugesagt, weshalb ich damit jetzt angefangen hab, aber das kann ma ja noch schnell ändern.

Und kann bitte wer über die CPU-Entity drüberschaun? - Bin mir bei manchen Datentypen nicht ganz sicher - habe mal Namen vergeben und auch in der Spec / Readme eingefügt.

Gruß FLo

**Comment by Phillip-W** [comment]
Bin auch für Integer is zwar etwas mehr schreib aufwand beim code, aber lässt sich einfacher nachvollziehen falls man mal einen fehler rekonstruieren möchte.

**Comment by Sabbuth** [comment]
Integer
