### ISSUE TITLE
IO Patrick

### ISSUE THREAD

**Issue by flomaurer** [Phillip-W/entwurf_vhdl_prozessor#20]
Uns fehlt noch das komplette IO aus der letzten Vorlesung;
das müssen wir gemeinsam machen -schaff ich heut nicht mehr.

**Comment by flomaurer** [comment]
Conversionpack fürs IO der OPCodes (cmd_image)

**Comment by Sabbuth** [comment]
ok, ich weiß nicht, wer was zu diesem Thema tun soll... wir sollten es diskutieren

**Comment by flomaurer** [comment]
Hi,
eigentlich hab ich da letzte Woche einfach ein jedem eine Funktion gegeben.
Jetzt hab ich gesehen, dass irgendwer so gut war und Integer'image gefunden hat.
Schau mal in den Masterbranch, da hab ich das auch nochmal kommentiert, weils nicht überall so geht.
Jetzt ists eh schon weniger.
Bereden wir heut um 6 - wenns früher infos brauchst ruf mich einfach auf Skype an - bin online
