### ISSUE TITLE
Test Load store

### ISSUE THREAD

**Issue by flomaurer** [Phillip-W/entwurf_vhdl_prozessor#22]
1. Vorlesung oder so Folie 28.

**Comment by flomaurer** [comment]
Wer schreibt die Tests?
Seite im Skript s.h. oben.

**Comment by ghost** [comment]
Ich kann versuchen, aber ich bin nicht sicher, dass ich richtig machen kann.

**Comment by flomaurer** [comment]
wär super - schau einfach mal ins skript, da steht, was am wichtigsten zu testen ist (1. oder 2. Vorlesung Seite 28)

Ansonsten wär es super, wenn wir im Zeitplan bleiben würden und alle ihre OPCodes schreiben - mit unserem IO sind wir eh hinten nach, das sollte seit 4 Tagen fertig sein.

**Comment by Phillip-W** [comment]
also ich habe alle variationen von load und store ausprobiert bei meinen tests funktioniert alles
