### ISSUE TITLE
generic Parameter

### ISSUE THREAD

**Issue by flomaurer** [Phillip-W/entwurf_vhdl_prozessor#3]
Unsere Parameter lagern wir in ein Package aus?
Darauf müssen wir ja öfter zugreifen und damit ist der Prozessor flexibler gestalltbar.
(Also meine Meinung)

**Comment by Phillip-W** [comment]
Stimme Zu
Die kann dann auch gleich jemand anlegen

**Comment by flomaurer** [comment]
Ich hab vor dem Namen meiner Entity en_ ... _ ... geschrieben.
Sprich wer die architecture dazu macht sollte ar_ ... _ ... oder so machen.
Und beim package halt auch im dateinamen pack_system_ ... oder sowas, damit man immer gleich weiß, um was für einen typ es sich handelt.

**Comment by Sabbuth** [comment]
ja immer alles in das selbe reinschreiben und aktualisieren. Das ist sehr wichtig

**Comment by flomaurer** [comment]
Hi Patrick,
die 2 Dateien, die du angelegt hast gibts schon.
Es gibt außer dem Masters zweig noch einen für die CPU. und da sind schon an Haufen dateien angelegt. 
Da ist auch von der Readme eine Kopie, in der schon paar namen für die Variablen eingetragen sind, damit das einheitlich wird.
Schau dir das evtl mal an.
Ich formatiere mal über deinen Text drüber.
