### ISSUE TITLE
IO FUnktionen

### ISSUE THREAD

**Issue by Sabbuth** [Phillip-W/entwurf_vhdl_prozessor#33]
Ich werde die IO Funktionen schreiben, die wir noch brauchen, mit Außnahme von hex_image und cmd_image.

Das ding muss ja irgendwann auch kompilierbar werden :)

Grüße
Patrick

**Comment by flomaurer** [comment]
super - jeder muss in seine OPCodes dann noch die entsprechende write_Befehle einbauen
