### ISSUE TITLE
Sype session heute?

### ISSUE THREAD

**Issue by Sabbuth** [Phillip-W/entwurf_vhdl_prozessor#79]
Hallo Leute,

wie wärse mit einem skype so gegen acht??

**Comment by flomaurer** [comment]
bin dabei - es hilft nur nix, wenn du uns nicht hinzufügst, dann gibst kein Mail. Hab ich jetzt gemacht

**Comment by Sabbuth** [comment]
ich kann erst ab 9 ´, wer ist dabei?

**Comment by Phillip-W** [comment]
ich bin den ganzen abend da.
kurz in skype anschreiben falls ich abwesend bin, damit ich kurz mein headset anschließen kann.

**Comment by flomaurer** [comment]
also bin dabei ruft mich einfach an - ich hoffe, dass ich den code bisdahin soweit hab, dass er funktioniert und nur mehr alle OP-Codes eingegeben werden müssen (ich schreib das nochmals neu und es funktioniert laut compiler)
