### ISSUE TITLE
Testen

### ISSUE THREAD

**Issue by flomaurer** [Phillip-W/entwurf_vhdl_prozessor#80]
TESTEN, TESTEN, TESTEN!!!

**Comment by flomaurer** [comment]
Also mein Teil ist soweit getestet. Nur bei den Flags bin ich mir nicht ganz sicher.
Evtl kann da noch jemand drüber schaun, weil ich nicht mehr da bin.
Gruß FLo

**Comment by flomaurer** [comment]
Also das Modell in Assembler funktioniert - nicht das in Assembler 2 oder Master.

**Comment by Phillip-W** [comment]
Mein Teil ist auch getestet und funktioniert einwandfrei

Das Modell im Master ist jetzt das aktuellste mit assambler und leis code
