### ISSUE TITLE
Assembler vervollständigen

### ISSUE THREAD

**Issue by flomaurer** [Phillip-W/entwurf_vhdl_prozessor#81]
Hi Patrick,
wann schreibst du den Rest meines Assembler Codes?
Ich wollt jetzt eigentlich testen.
Ansonsten schreib ich den Teil, den ich brauch selbst.
Gruß FLo

**Comment by flomaurer** [comment]
Hi, ich schreib meinen Teil jetzt selber.
Schönen Abend.

**Comment by Sabbuth** [comment]
Hi Flo,

ich wollte jetzt anfangen. Bist Du schon dran?

**Comment by Sabbuth** [comment]
Wenn ja, lade es hoch und ich mache dort weiter.

**Comment by flomaurer** [comment]
bin schon voll dabei und eig fertig - muss noch kurz 4 Fehler rausmachen.
Das war mit CopyPaste so schnell - schreibs einfach auf dich den Teil. Ist ja wurscht.

**Comment by flomaurer** [comment]
schaus dir an - ist online - weiß nicht, obs richtig ist.

Ich bin die nächsten Tage nicht da. Sprich ich werde meinen Teil Testen und macht ihr bitte aus, wie das mit Leis Teil wird.

Bei meinem Teil bin ich mir mit den Flags nicht ganz sicher.
